const tableCompetitions = [
  {
    competitionId: 1,
    season: "2023",
    championship: "Départemental",
    category: "11/12 ans",
    gender: "Garçons",
    teams: [
      {
        teamNum: 1,
        level: "Division 1",
        group: "D",
        path: "https://tenup.fft.fr/championnat/82346138?division=116140&phase=185154&poule=426561",
        players: [
          {
            playerName: "Aaaaaaaaaa Bbbbbbbbbbb",
            email: "b",
            tel: "1",
            ranking: "30/3",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "Bbbbbbbbbbb Cccccccccccc",
            email: "c",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "2",
            licenceNum: "4",
          },
          {
            playerName: "Cccccccccccc Dddddddddddd",
            email: "c",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "2",
            licenceNum: "4",
          },
          {
            playerName: "Dddddddddddd Eeeeeeeeeee",
            email: "c",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "2",
            licenceNum: "4",
          },
        ],
      },
      {
        teamNum: 2,
        level: "Division 2",
        group: "E",
        path: "https://tenup.fft.fr/championnat/82346138?division=116141&phase=185155&poule=426566",
        players: [
          {
            playerName: "Ggggggggggg Hhhhhhhhhh",
            email: "d",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "3",
            licenceNum: "4",
          },
          {
            playerName: "Hhhhhhhhhh Iiiiiiiii",
            email: "a",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
  {
    competitionId: 2,
    season: "2023",
    championship: "Départemental",
    category: "15/18 ans",
    gender: "Garçons",
    teams: [
      {
        teamNum: 1,
        level: "Division 3",
        group: "C",
        path: "https://tenup.fft.fr/championnat/82346141?division=116577&phase=185770&poule=427690",
        players: [
          {
            playerName: "Ddddddddddd Eeeeeeeeee",
            email: "b",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "Eeeeeeeeee Ffffffff",
            email: "c",
            tel: "1",
            ranking: "30/4",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
  {
    competitionId: 3,
    season: "2023",
    championship: "Départemental",
    category: "15/18 ans",
    gender: "Filles",
    teams: [
      {
        teamNum: 1,
        level: "Division 1",
        group: "1",
        path: "https://tenup.fft.fr/championnat/82346140?division=116572&phase=185763&poule=427621",
        players: [
          {
            playerName: "A",
            email: "b",
            tel: "1",
            ranking: "2",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "B",
            email: "c",
            tel: "1",
            ranking: "2",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
  {
    competitionId: 4,
    season: "2023",
    championship: "Coupe Henry Genéty",
    category: "13/14 ans",
    gender: "Mixte",
    teams: [
      {
        teamNum: 1,
        level: "Division 1",
        group: "A",
        path: "https://tenup.fft.fr/championnat/82367960?division=119945&phase=191721&poule=438110",
        players: [
          {
            playerName: "GRANGER Noémie",
            email: "vergranger@orange.fr",
            tel: "06.25.70.61.32",
            ranking: "30/3",
            rankingDouble: "15",
            licenceNum: "4540484 H",
          },
          {
            playerName: "SALGADO Rafael",
            email: "gmarechal01@gmail.com",
            tel: "06.43.84.05.43",
            ranking: "30/3",
            rankingDouble: "15",
            licenceNum: "4546267 U",
          },
          {
            playerName: "ALBAN Quentin",
            email: "alban.ceciliaetstephane@neuf.fr",
            tel: "06.73.24.76.98",
            ranking: "40",
            rankingDouble: "18",
            licenceNum: "8022720 X",
          },
          {
            playerName: "PANIE César",
            email: "jeromepanie@gmail.com",
            tel: "06.88.32.78.49",
            ranking: "40",
            rankingDouble: "18",
            licenceNum: "4544557 K",
          },
        ],
      },
    ],
  },
  {
    competitionId: 5,
    season: "2023",
    championship: "Ligue",
    category: "Seniors",
    gender: "Messieurs",
    teams: [
      {
        teamNum: 1,
        level: "Ligue 3",
        group: "H",
        path: "https://tenup.fft.fr/championnat/82335989?division=114404&phase=182814&poule=439245",
        players: [
          {
            playerName: "A",
            email: "b",
            tel: "1",
            ranking: "2",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "B",
            email: "c",
            tel: "1",
            ranking: "2",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
  {
    competitionId: 6,
    season: "2023",
    championship: "Interdépartemental",
    category: "Seniors 35+",
    gender: "Dames",
    teams: [
      {
        teamNum: 1,
        level: "Division 2",
        group: "T",
        path: "https://tenup.fft.fr/championnat/82336005?division=115087&phase=183775&poule=424659",
        players: [
          {
            playerName: "A",
            email: "b",
            tel: "1",
            ranking: "2",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "B",
            email: "c",
            tel: "1",
            ranking: "2",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
  {
    competitionId: 7,
    season: "2023",
    championship: "Interdépartemental",
    category: "Seniors 35+",
    gender: "Messieurs",
    teams: [
      {
        teamNum: 1,
        level: "Division 3",
        group: "F",
        path: "https://tenup.fft.fr/championnat/82336006?division=114639&phase=183145&poule=425130",
        players: [
          {
            playerName: "A",
            email: "b",
            tel: "1",
            ranking: "2",
            doubleRanking: "2",
            licenceNum: "2",
          },
          {
            playerName: "B",
            email: "c",
            tel: "1",
            ranking: "2",
            doubleRanking: "3",
            licenceNum: "4",
          },
        ],
      },
    ],
  },
];

export default tableCompetitions;
