import badminton from "../assets/img/imganimations/01_badminton_1920.jpg";
import venteFromageVin from "../assets/img/imganimations/02_venteFromageVin.jpg";
import tournoiInterne from "../assets/img/imganimations/04_tennis-raquettes_1920.jpg";
import programme from "../assets/img/imganimations/05_programme.jpg";
import pickleball from "../assets/img/imganimations/06_pickleball_1920.jpg";
import ecoleTennis from "../assets/img/imganimations/07_ecoleTennis_1920.jpg";
import soireeClub from "../assets/img/imganimations/08_soireeClub_1920.png";
import rolandGarros from "../assets/img/imganimations/09_rolandGarros_1920.jpg";

const tableAnimations = [
  {
    id: 1,
    image: "",
    animation: "Assemblée Générale",
    desc: "En tant que membre du club vous êtes convié. Venez nombreux ...",
    dateDebut: "2022-10-15",
    dateFin: "2022-10-15",
    lieu: "Clubhouse de 19h à 20h",
  },
  {
    id: 2,
    image: pickleball,
    animation: "Pickleball",
    desc: "Journée détente en pratiquant une activité accessible à tous ...",
    dateDebut: "2022-11-19",
    dateFin: "2022-11-19",
    lieu: "Courts couverts",
  },
  {
    id: 3,
    image: soireeClub,
    animation: "Repas de fin d'année",
    desc: "Tous les membres intéressés sont invités. Faites-vous connaître ...",
    dateDebut: "2022-12-09",
    dateFin: "2022-12-09",
    lieu: "Pizzeria au feu de bois",
  },
  {
    id: 4,
    image: venteFromageVin,
    animation: "Vente de Fromages du Jura - Vins du Beaujolais",
    desc: "Commandes de Noël à passer avant le 10 décembre ...",
    dateDebut: "2022-12-17",
    dateFin: "2022-12-17",
    lieu: "Maison des associations",
  },
  {
    id: 5,
    image: tournoiInterne,
    animation: "Doubles de Noël",
    desc: "Compétition amicale avec changement de partenaire à chaque double ...",
    dateDebut: "2022-12-19",
    dateFin: "2022-12-19",
    lieu: "Courts couverts",
  },
  {
    id: 6,
    image: programme,
    animation: "Soirée cartes",
    desc: "Soirée privée réservez aux membres du club et leurs amis ...",
    dateDebut: "2023-02-24",
    dateFin: "2023-02-24",
    lieu: "Clubhouse – 19h",
  },
  {
    id: 7,
    image: badminton,
    animation: "Tournoi de Badminton",
    desc: "Tournoi de la St Patrick - Ouvert à tous. Venez nombreux avec vos amis ...",
    dateDebut: "2023-03-11",
    dateFin: "2023-03-11",
    lieu: "Salle polyvalente",
  },
  {
    id: 8,
    image: venteFromageVin,
    animation: "Vente de Fromages du Jura - Vins du Beaujolais",
    desc: "Commandes à passer avant le 15 mars ...",
    dateDebut: "2023-04-01",
    dateFin: "2023-04-01",
    lieu: "Maison des associations",
  },
  {
    id: 9,
    image: rolandGarros,
    animation: "Sortie Roland Garros",
    desc: "Organisation du covoiturage pour une journée commune à RG ...",
    dateDebut: "2023-06-02",
    dateFin: "2023-06-02",
    lieu: "Départ clubhouse – 6h",
  },
  {
    id: 10,
    image: tournoiInterne,
    animation: "Tournoi interne",
    desc: "Tournoi homologué réservé aux membres du club ...",
    dateDebut: "2023-03-01",
    dateFin: "2023-07-01",
    lieu: "Courts couverts et extérieurs",
  },
  {
    id: 11,
    image: tournoiInterne,
    animation: "38ème tournoi open NC à 4-6",
    desc: "Tournoi homologué ouvert à tous les licenciés ...",
    dateDebut: "2023-06-09",
    dateFin: "2023-06-25",
    lieu: "Courts extérieurs",
  },
  {
    id: 12,
    image: ecoleTennis,
    animation: "Fête de l’école de Tennis",
    desc: "Jeux et démonstrations des jeunes de l'école de tennis ...",
    dateDebut: "2023-06-28",
    dateFin: "2023-06-28",
    lieu: "Courts extérieurs",
  },
  {
    id: 13,
    image: soireeClub,
    animation: "Fête du Tennis Club",
    desc: "Repas de fin d'année entre membres et amis du club ...",
    dateDebut: "2023-07-01",
    dateFin: "2023-07-01",
    lieu: "Clubhouse",
  },
  {
    id: 14,
    image: ecoleTennis,
    animation: "Stages d'été - Enfants",
    desc: "Première semaine de stage pour enfants. Inscrivez-vous auprès de Fréd ...",
    dateDebut: "2023-07-10",
    dateFin: "2023-07-14",
    lieu: "Courts extérieurs et couverts",
  },
  {
    id: 15,
    image: ecoleTennis,
    animation: "Stages d'été - Enfants",
    desc: "Deuxième semaine de stage pour enfants. Inscrivez-vous auprès de Fréd ...",
    dateDebut: "2023-07-17",
    dateFin: "2023-07-21",
    lieu: "Courts extérieurs et couverts",
  },
  {
    id: 16,
    image: ecoleTennis,
    animation: "Stages d'été - Enfants",
    desc: "Troisième semaine de stage pour enfants. Inscrivez-vous auprès de Fréd ...",
    dateDebut: "2023-07-24",
    dateFin: "2023-07-28",
    lieu: "Courts extérieurs et couverts",
  },
  {
    id: 17,
    image: soireeClub,
    animation: "Jumelage TC Bad Waldsee",
    desc: "Weekend festif au club de tennis de Bad Waldsee",
    dateDebut: "2023-07-14",
    dateFin: "2023-07-14",
    lieu: "Départ Clubhouse",
  },
  {
    id: 18,
    image: tournoiInterne,
    animation: "TTJ-01 Tournoi jeunes",
    desc: "Galaxie Orange - Vert, tableaux 11/12-13/14-15/16 ans",
    dateDebut: "2023-08-19",
    dateFin: "2023-08-26",
    lieu: "Courts extérieurs",
  },
];

export default tableAnimations;
